CREATE TABLE produto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(100)   NOT NULL,
    descricao  VARCHAR(255),
    preco      DECIMAL(10, 2) NOT NULL,
    quantidade INT            NOT NULL
);

CREATE TABLE pedido
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_pedido TIMESTAMP NOT NULL
);

CREATE TABLE pedido_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INT    NOT NULL,
    id_pedido  BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    CONSTRAINT fk_pedido_item_pedido FOREIGN KEY (id_pedido) REFERENCES pedido (id),
    CONSTRAINT fk_pedido_item_produto FOREIGN KEY (id_produto) REFERENCES produto (id)
);